export const FILTER_CHEAP_TICKET = 'FILTER_CHEAP_TICKET'
export const FILTER_FAST_TICKET = 'FILTER_FAST_TICKET'

export const CHECKBOX_ALL_TICKETS = 'CHECKBOX_ALL_TICKETS'
export const CHECKBOX_NON_STOP_TICKETS = 'CHECKBOX_NON_STOP_TICKETS'
export const CHECKBOX_ONE_STOP_TICKETS = 'CHECKBOX_ONE_STOP_TICKETS'
export const CHECKBOX_TWO_STOP_TICKETS = 'CHECKBOX_TWO_STOP_TICKETS'
export const CHECKBOX_THREE_STOP_TICKETS = 'CHECKBOX_THREE_STOP_TICKETS'

export const FETCH_USER_ID_REQUEST = 'FETCH_USER_ID_REQUEST'
export const FETCH_USER_ID_SUCCESS = 'FETCH_USER_ID_SUCCESS'
export const FETCH_USER_ID_FAILURE = 'FETCH_USER_ID_FAILURE'

export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE'

export const MORE_TICKETS = 'MORE_TICKETS'
