export const FILTER_CHEAP_TICKET = "FILTER_CHEAP_TICKET";
export const FILTER_FAST_TICKET = "FILTER_FAST_TICKET";

export const CHECKBOX_ALL_TICKETS = "CHECKBOX_ALL_TICKETS";
export const CHECKBOX_NON_STOP_TICKETS = "CHECKBOX_NON_STOP_TICKETS";
export const CHECKBOX_ONE_STOP_TICKETS = "CHECKBOX_ONE_STOP_TICKETS";
export const CHECKBOX_TWO_STOP_TICKETS = "CHECKBOX_TWO_STOP_TICKETS";
export const CHECKBOX_THREE_STOP_TICKETS = "CHECKBOX_THREE_STOP_TICKETS";
